#!/bin/bash

set -eo pipefail

case "${1}" in
    configure|upgrade|reinstall ) ;;

    *                           )
        echo "postinst called with unknown argument: $1" >&2
        exit 1
    ;;
esac
