#!/bin/bash

set -eo pipefail

case "${1}" in
    remove|deconfigure                                                  ) ;;
    upgrade|configure                                                   ) ;;
    failed-upgrade|abort-install|abort-remove|abort-upgrade|disappear   ) ;;
    *                                                                   )
        echo "prerm called with unknown argument: $1" >&2
        exit 1
    ;;
esac
